#ifndef DATETIMEENUM_INCLUDED
#define DATETIMEENUM_INCLUDED

enum ENUM_TIME_TYPE
{
  TIME_TYPE_DAY,
  TIME_TYPE_WEEK,
  TIME_TYPE_MONTH,
  TIME_TYPE_YEAR,
  TIME_TYPE_ALL
};

#endif /* DATETIMEENUM_INCLUDED */
